apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: newk8scluster
  region: ap-south-1
  version: "1.23"
nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    maxSize: 2
    minSize: 1
    volumeSize: 30
    volumeType: gp3
    ssh:
      allow: true
  - name: ng-2
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 30
    volumeType: gp3
    ssh:
      allow: true

      #       eksctl create cluster -f eks-cluster.yaml
#
 #eksctl create nodegroup --config-file=eks-cluster.yaml
 #
 # eksctl delete cluster -f eks-cluster.yaml
#
 #eksctl delete nodegroup --config-file=eks-cluster.yaml
