apiVersion: v1
kind: Service
metadata:
   name: mystate-svc
spec:
    clusterIP: None
    selector:
      app: myapp
    ports:
    - port: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: web
spec:
   serviceName: "mystate-svc"
   replicas: 3
   selector:
      matchLabels:
        app: myapp
   template:
      metadata:
         labels:
           app: myapp
      spec:
           containers:
           - name: con1
             image: nginx:latest
             ports:
             - containerPort: 80
---
---
apiVersion: v1
kind: Service
metadata:
   name: mydep-svc
spec:
    selector:
      app: myapp
    ports:
    - port: 80
---

