apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-dep
spec:
   replicas: 1
   selector:
      matchLabels:
        app: myapp
   template:
      metadata:
         labels:
           app: myapp
      spec:
           containers:
           - name: con1
             image: wordpress:latest
             ports:
             - containerPort: 80
             resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
---
---
apiVersion: v1
kind: Service
metadata:
   name: mydep-svc
spec:
    type: NodePort
    selector:
      app: myapp
    ports:
    - port: 80
      nodePort: 30126
