apiVersion: apps/v1
kind: Deployment
metadata:
    name: mywp
spec:
   replicas: 1
   selector:
      matchLabels:
        app: myapp
   template:
      metadata:
         labels:
           app: myapp
      spec:
           containers:
           - name: con1
             image: wordpress:latest
             ports:
             - containerPort: 80
             envFrom:
             - configMapRef:
                   name: mywpcf  
             resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
             livenessProbe:
               httpGet:
                 path: /
                 port: 80
               initialDelaySeconds: 30
               periodSeconds: 10
        
---
---
apiVersion: v1
kind: Service
metadata:
   name: mydep-svc
spec:
    type: NodePort
    selector:
      app: myapp
    ports:
    - port: 80
      nodePort: 30126
